<?php
$param = $block->getProductCollection();
?>

<?php if (($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $block->loadItemsByProductCollection($block->getProductCollection());

    $type = 'ac-crosssell';
    $mode = 'carusel';
    $image = 'category_page_grid';

    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;

    $config = $this->helper('Accord\General\Helper\Config\Catalog\General');
    if ($isDisplaySkuOnCatalogue = $config->isDisplaySkuOnCatalogue()) {
        $skuDisplayLabel = $config->getSkuDisplayLabel();
    }
    ?>
    <div class="block widget block-products-list <?= $mode ?> <?= $type ?>">

        <?php if ($title): ?>
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */
                    echo $title; ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */
            echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */
            echo $mode; ?> <?php /* @escapeNotVerified */
            echo $mode; ?>">
                <div
                    class="product-items product-items_custom <?php /* @escapeNotVerified */
                    echo $type; ?>">
                    <?php foreach ($items as $_product): ?>
                        <?php if($_product->getId() == $block->getData('product_id')){ continue;} ?>
                        <div class="product-item">
                            <?php
                            $scope = 'ko_itemGrid_' . rand(10, 100000); // maybe sku
                            ?>
                            <div
                                data-bind="scope: '<?= $scope ?>'"
                                class="product-item-info">
                                <a href="<?php /* @escapeNotVerified */
                                echo $block->getProductUrl($_product) ?>" class="product-item-photo">
                                    <?php echo $block->getImageCustom($_product, $image)->toHtml(); ?>
                                </a>
                                <div class="product-item-details">
                                    <div data-product-id="<?php echo $_product->getId()?>"></div>
                                    <strong class="product-item-name">
                                        <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */
                                           echo $block->getProductUrl($_product) ?>"
                                           class="product-item-link">
                                            <?php echo $block->escapeHtml($_product->getName()) ?>
                                        </a>
                                    </strong>

                                    <div class="origin-country">
                                        <p>
                                            <?php echo $_product->getData('ac_region')?>
                                            <?php
                                            if($_product->getData('ac_suitable_for')) {
                                                $options = explode(',', $_product->getData('ac_suitable_for'));
                                                $label = '';
                                                foreach ($options as $_optionId) {
                                                    $attr = $_product->getResource()->getAttribute('ac_suitable_for');
                                                    if ($attr->usesSource()) {
                                                        $optionText = $attr->getSource()->getOptionText($_optionId);
                                                        if ($label == '') {
                                                            $label .= $optionText;
                                                        } else {
                                                            $label .= ',' . $optionText;
                                                        }
                                                    }
                                                }
                                                if($label){
                                                    echo '/'.$label;
                                                }
                                            }
                                            ?>
                                        </p>
                                    </div>

                                    <div class="clearfix product-item__review-wr">
                                        <!-- rating -->
                                        <?php if ($templateType): ?>
                                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
                                        <?php endif; ?>
                                    </div>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>

                                        <div class="product-item-actions">
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $compareHelper->getPostDataParams($_product); ?>'
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to compare') ?>">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $block->getAddToWishlistParams($_product); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?php /* @escapeNotVerified */
                                                           echo __('Add to wish list') ?>">
                                                        <span><?php /* @escapeNotVerified */
                                                            echo __('Add to wish list') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>

                                            <!-- ko template: "Accord_Ui/inc/priceWidget"--><!-- /ko -->

                                            <div class="product-item-bottom">
                                                <?php if ($block->shouldRenderQuantity()): ?>

                                                    <!-- qty -->
                                                    <div class="qty__wr">
                                                        <!-- ko template: "Accord_Ui/inc/qtyWidget"--><!-- /ko -->
                                                    </div>

                                                    <!-- ko template: "Accord_Ui/inc/qtyTypeWidget"--><!-- /ko -->


                                                <?php endif; ?>

                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php
                                                        /**
                                                         * @see magento/app/code/Accord/Ui/view/frontend/web/template/itemAjaxSubs.html
                                                         */
                                                        ?>

                                                        <?php if ($_product->isSaleable()): ?>
                                                            <!-- ko template: "Accord_Ui/inc/addCart"--><!-- /ko -->
                                                        <?php else: ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div
                                                                    class="stock available"><span><?php /* @escapeNotVerified */
                                                                        echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div
                                                                    class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                        echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>

                                                    </div>
                                                <?php endif; ?>
                                            </div>

                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <script type="text/x-magento-init">
                            {
                                "*": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "<?= $scope ?>": {
                                                "templateLineMessage": "Accord_Ui/lineMessage",
                                                "component": "Accord_Ui/ko/itemGrid",
                                                "data": <?= json_encode($block->decorateProduct($_product)) ?>
                                            }
                                        }
                                    }
                                }
                            }
                        </script>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
