on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: https://repo.magento.com/
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      PROJECT_NAME: Accord
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: GruzinskiiArtem/githubactions@v27
        run: /magento2 php vendor/phpunit/phpunit/phpunit -c ./tools/phpunit/phpunit.xml
