on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: https://repo.magento.com/
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      PROJECT_NAME: Accord
    name: A job to say hello
    steps:
      - uses: GruzinskiiArtem/githubactions@v36
      - run: ls -la
          
      - name: Run Unit TestsfsFS
        run: "ls -la"
      - name: Run Unit Tests
        run: "cd /magento2/tools/phpunit && ../../vendor/bin/phpunit -c phpunit.xml"
