on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_URL: https://repo.magento.com/
      MAGENTO_MARKETPLACE_USERNAME: ${{ secrets.MAGENTO_MARKETPLACE_USERNAME }}
      MAGENTO_MARKETPLACE_PASSWORD: ${{ secrets.MAGENTO_MARKETPLACE_PASSWORD }}
      PROJECT_NAME: Accord
    name: A job to say hello
    steps:
      - name: Hello world action step
        uses: GruzinskiiArtem/githubactions@v31
      - name: Run Unit Tests
        run: cd ${MAGENTO_ROOT}/tools/phpunit && ../../vendor/bin/phpunit -c phpunit.xml